FROM node:alpine

# Create app directory
WORKDIR /home/ubuntu/file

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copie                                                                             d
# where available (npm@5+)
COPY ./ /home/ubuntu/file

RUN npm install
# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
CMD [ "node", "server.js" ]
